### ISSUE TITLE
Default snapshot size is not respected

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-mayavi#52]
Running tests on an ubuntu VM connected through vpn the snapshot tests fail with the following tracebacks.

``` python
simphony_mayavi.tests.test_snapshot.TestSnapShot

======================================================================
FAIL: test_lattice_snapshot (simphony_mayavi.tests.test_snapshot.TestSnapShot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kaitsu/simphony-mayavi/simphony_mayavi/tests/test_snapshot.py", line 31, in test_lattice_snapshot
    self.assertImageSavedWithContent(filename)
  File "/home/kaitsu/simphony-mayavi/simphony_mayavi/tests/test_snapshot.py", line 67, in assertImageSavedWithContent
    self.assertEqual(image.shape[:2], (600, 800))
AssertionError: Tuples differ: (320, 400) != (600, 800)

First differing element 0:
320
600

- (320, 400)
+ (600, 800)

======================================================================
FAIL: test_mesh_snapshot (simphony_mayavi.tests.test_snapshot.TestSnapShot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kaitsu/simphony-mayavi/simphony_mayavi/tests/test_snapshot.py", line 45, in test_mesh_snapshot
    self.assertImageSavedWithContent(filename)
  File "/home/kaitsu/simphony-mayavi/simphony_mayavi/tests/test_snapshot.py", line 67, in assertImageSavedWithContent
    self.assertEqual(image.shape[:2], (600, 800))
AssertionError: Tuples differ: (320, 400) != (600, 800)

First differing element 0:
320
600

- (320, 400)
+ (600, 800)

======================================================================
FAIL: test_particles_snapshot (simphony_mayavi.tests.test_snapshot.TestSnapShot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kaitsu/simphony-mayavi/simphony_mayavi/tests/test_snapshot.py", line 59, in test_particles_snapshot
    self.assertImageSavedWithContent(filename)
  File "/home/kaitsu/simphony-mayavi/simphony_mayavi/tests/test_snapshot.py", line 67, in assertImageSavedWithContent
    self.assertEqual(image.shape[:2], (600, 800))
AssertionError: Tuples differ: (320, 400) != (600, 800)

First differing element 0:
320
600

- (320, 400)
+ (600, 800)

----------------------------------------------------------------------
Ran 32 tests in 16.228s

FAILED (failures=3)
```

**Comment by itziakos** [comment]
More info from @khiltunen on the machine specs where the issue is seen
- KVM virtualization on AMD Opteron machine running Centos 6.6
- currently no 3D acceleration
- vncserver running on another linux box from which connected to VM using ssh -X
- vncserver screen resolution 1680x1050
- Mayavi version 4.3.1 
- VTK version 5.8.0
- Python 2.7.3 
- wxPython 2.8.12.1

**Comment by kitchoi** [comment]
I was just able to reproduce this.  This may be caused by backend being wxPython.  Need more investigate to confirm.

**Comment by kitchoi** [comment]
I have a working branch on mayavi that solves this problem.

**Comment by stefanoborini** [comment]
status of this?

**Comment by kitchoi** [comment]
I fixed it on a headed machine, but get the usual ill rendering on the headless travis (related to #34 which I gave up fixing).  Try enthought/mayavi/fix-savefig-wx branch if you'd like to.

**Comment by stefanoborini** [comment]
Cannot reach this point on travis. It turns out that issuing GLX-related requests on the xvfb terminates the process:

```
test_lattice_snapshot (simphony_mayavi.tests.test_snapshot.TestSnapShot) ... The program 'python2.7' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContextTag'.
  (Details: serial 150 error_code 157 request_code 147 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Rumors have that it should render an "empty" image, but it doesn't seem to be the case.

**Comment by kitchoi** [comment]
Could we allocate tests that should be run on the dev's/user's machine but not on travis due to hardware issue?

**Comment by kitchoi** [comment]
On the other hand, it is possible that the fix in the enthought/mayavi/fix-savefig-wx is wrong.

**Comment by kitchoi** [comment]
Reverted mayavi #331 for more thorough review.  Reopening this issue.
